### ISSUE TITLE
status assertion removed in v4 still documented

### ISSUE THREAD

**Issue by focusaurus** [shouldjs/shouldjs.github.io#2]
AFAICT `.should.have.status(code)` was removed back in v4 but it is still present in the documentation.

**Comment by btd** [comment]
It is not, see https://github.com/shouldjs/http/blob/master/http.js#L45

**Comment by focusaurus** [comment]
Ah, so is it only available if I `require('should-http')`?

**Comment by btd** [comment]
Yep, exactly
